USE [master]
GO

/****** Object:  Database [HD_meat]    Script Date: 10.12.2024 19:32:56 ******/
CREATE DATABASE [HD_meat]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HD_meat_Data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER_HD\MSSQL\DATA\HD_meat_Data.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'HD_meat_Log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER_HD\MSSQL\DATA\HD_meat_Log.ldf' , SIZE = 3072KB , MAXSIZE = 2048GB , FILEGROWTH = 1024KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HD_meat].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HD_meat] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HD_meat] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HD_meat] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HD_meat] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HD_meat] SET ARITHABORT OFF 
GO

ALTER DATABASE [HD_meat] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HD_meat] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HD_meat] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HD_meat] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HD_meat] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HD_meat] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HD_meat] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HD_meat] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HD_meat] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HD_meat] SET  ENABLE_BROKER 
GO

ALTER DATABASE [HD_meat] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HD_meat] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HD_meat] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HD_meat] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HD_meat] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HD_meat] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HD_meat] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HD_meat] SET RECOVERY FULL 
GO

ALTER DATABASE [HD_meat] SET  MULTI_USER 
GO

ALTER DATABASE [HD_meat] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HD_meat] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HD_meat] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HD_meat] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HD_meat] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HD_meat] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [HD_meat] SET QUERY_STORE = ON
GO

ALTER DATABASE [HD_meat] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [HD_meat] SET  READ_WRITE 
GO

